// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IPasswordCrypt is an autogenerated mock type for the IPasswordCrypt type
type IPasswordCrypt struct {
	mock.Mock
}

// Encode provides a mock function with given fields: password
func (_m *IPasswordCrypt) Encode(password string) (string, error) {
	ret := _m.Called(password)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Verify provides a mock function with given fields: hashedPassword, password
func (_m *IPasswordCrypt) Verify(hashedPassword string, password string) error {
	ret := _m.Called(hashedPassword, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(hashedPassword, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIPasswordCrypt interface {
	mock.TestingT
	Cleanup(func())
}

// NewIPasswordCrypt creates a new instance of IPasswordCrypt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIPasswordCrypt(t mockConstructorTestingTNewIPasswordCrypt) *IPasswordCrypt {
	mock := &IPasswordCrypt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
