// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IChecker is an autogenerated mock type for the IChecker type
type IChecker struct {
	mock.Mock
}

// String provides a mock function with given fields: strings, predicate
func (_m *IChecker) String(strings []string, predicate func(string) bool) error {
	ret := _m.Called(strings, predicate)

	var r0 error
	if rf, ok := ret.Get(0).(func([]string, func(string) bool) error); ok {
		r0 = rf(strings, predicate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIChecker interface {
	mock.TestingT
	Cleanup(func())
}

// NewIChecker creates a new instance of IChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIChecker(t mockConstructorTestingTNewIChecker) *IChecker {
	mock := &IChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
